// -- 96강 왕초보 영어회화 강의 데이터 --
// 출처: 라이브 아카데미 토들러 유튜브 재생목록 '기초 문장 만들기와 내용 확장'
// https://www.youtube.com/playlist?list=PLEzsBdrpZXC8tdzAqQHEQ66TocGI-Kagh
const LESSON96 = [
  { n: 1, id: "OGHo7apPWIY", title: "왕초보를 위한 영어회화 강의 - Lesson 001 [기본적인 문장 구성하기]" },
  { n: 2, id: "yJg0rrmRZhA", title: "🌱영어회화 | 기초 영어 - 문장 만들기-  Lesson 002" },
  { n: 3, id: "0R6tL0ESm_U", title: "기초 영어 | Lesson 003 | 실제 회화에서 be 동사의 기본적인 활용" },
  { n: 4, id: "c7_IqzxcaS0", title: "기초 영어 | Lesson 004 | 현재 / 과거 / 미래 시제" },
  { n: 5, id: "MY6Y2wiXSLA", title: "영어회화 | 기초 문장 구성하기 [Lesson 005] | be 동사로 인상 표현하기 + 과거/미래시제 적용" },
  { n: 6, id: "kOi2P-HQIKs", title: "\"~하고 싶다\", \"해야 된다\"를 영어로 말하기 | 영어 기초 문장 구성하기 | 영어회화 [LESSON 006]" },
  { n: 7, id: "_FeHK1Vd7KM", title: "영어로 질문하기 [Part1] - 기초적인 의문형/의문문 구성을 배워보자 | 영어회화 [LESSON 007]" },
  { n: 8, id: "MDLG58YRPv4", title: "영어로 질문하기 [Part 2] [ LESSON #008 ] -- 초보영어회화 | 라이브 아카데미 토들러" },
  { n: 9, id: "pOggApqOz3Y", title: "영어로 질문하기 [Part 3] [ LESSON #009 ] -- 영어회화 | 라이브 아카데미 토들러" },
  { n: 10, id: "uPWsw5GIbtI", title: "[LESSON#10] - 영어 문장 연결하기 [PART 1]- and / so / because - [라이브 아카데미 토들러]" },
  { n: 11, id: "wjXyGcnx2G8", title: "[LESSON #11] 문맥을 만들어서 자연스러운 말의 흐름 익히기 - and / so / because - PART 2 [기초 영어회화]" },
  { n: 12, id: "lIwZ3bkyr6s", title: "[LESSON#12] and / so / because 추가연습 - PART 3 | 영어회화 [라이브아카데미 토들러]" },
  { n: 13, id: "WSUM2yUsub8", title: "[LESSON #13 - PART 1] \"무엇이 있다/없다\" - there is(are) ~ there is(are) no ~" },
  { n: 14, id: "5nwOP4D__rw", title: "\"there is\" - PART 2 [ LESSON #14 ] - 영어회화" },
  { n: 15, id: "Xg1fjoe0cXo", title: "[ LESSON #15 ] 영어회화 - 기초 문장 구성 - \"무엇을 하기 + 어떻다\"" },
  { n: 16, id: "hyHjOMAPmMs", title: "[ LESSON #16 ] something / somewhere / someone - 영어회화 기초 [라이브아카데미 토들러]" },
  { n: 17, id: "rFGmMnQFQaw", title: "[ LESSON #17 - PART 1 ] \"시간이 걸리다\", \"돈이 들다\" - [ 영어회화 / 라이브아카데미 토들러 ]" },
  { n: 18, id: "_49xUFx5n4M", title: "[ LESSON#17 - PART 2 ] - \"오래 걸려요?\" / \"얼마나 (오래) 걸려요?\"" },
  { n: 19, id: "dpN0FfT8k7o", title: "[ LESSON #18 ] - 할 때 / 하기 전에 / 하고 나서 / 할 때까지 [ 라이브아카데미 토들러 / 영어회화 ]" },
  { n: 20, id: "tgAnPN_mf-k", title: "[LESSON#19 - Part 1] -  과거분사형 / 동명사형 - bored/boring" },
  { n: 21, id: "Ks0qJXeTCcA", title: "[ LESSON #19 - PART 2 ] \"짜증나\" - annoyed / annoying / frustrated / frustrating" },
  { n: 22, id: "cHJpKhVnH-I", title: "[ LESSON #20 / 대화가이드 #003 ] - \"할게 있다/없다/많다\" - \"그때까지는 할게 별로 없다\"" },
  { n: 23, id: "F8vUB75aD34", title: "[ LESSON #21 ] - 예전에는 ~~ 었는데 지금은 ~~ | 자연스러운 말의 흐름 | 영어회화" },
  { n: 24, id: "yvWkEoHCdmE", title: "[ LESSON #22 ] - 중요한 영어 단어 \"spend\" - Part 1" },
  { n: 25, id: "vsoQ-MWFGZc", title: "[ LESSON #23 ] 'spend'  - Part 2 [ 영어회화 ]" },
  { n: 26, id: "l_OIS5XaQCs", title: "LESSON #24 - 시간표현 PART 1 - 며칠 전에 / 몇달 후에 / 지금으로부터 몇년 뒤에 / 그저께(엊그제) / 모레" },
  { n: 27, id: "vPpsH30SmZs", title: "감각동사 - PART 1 (기본개념) - look, sound, smell, taste, feel" },
  { n: 28, id: "lo4YD4FASOM", title: "감각동사 - PART 2 - look like + 명사 / sound like + 완성형 문장" },
  { n: 29, id: "GHlSaB3VzRE", title: "감각동사 PART 3 - 응용연습" },
  { n: 30, id: "KvuCt-u56Ww", title: "감각동사 - PART 4 - \"내가 보기에는 괜찮은데.\" , \"너가 듣기에는 어때?\"" },
  { n: 31, id: "xY8-tOJu0GQ", title: "관계절 - PART 1 - 기본개념과 기본 구성 이해하기" },
  { n: 32, id: "Iux513BJWLo", title: "관계절 PART 2 - 내가 듣는 음악, 내가 찾던 디자인, 새로 이사한 집" },
  { n: 33, id: "_2RMoPE92VY", title: "관계절 - PART 3 - 미국에 사는 친구 / 수영장이 있는 호텔 / 개봉하지 않은 영화" },
  { n: 34, id: "LhLO4mwkac8", title: "[ 대화가이드 #004 ] 관계절 - PART 4 - 자연스러운 대화 속에서 관계절을 연습하고 감잡기" },
  { n: 35, id: "W3V9TM6Vrj0", title: "[ 생활 영어 표현 ] \"거기는 음식이 맛있어\"를 영어로 표현하는 3가지 방식" },
  { n: 36, id: "HsmLR7rZtTg", title: "(무엇)이 많다 / (무엇)을 많이 한다 - \"a lot of\"" },
  { n: 37, id: "4IuQ53h9dwQ", title: "[ 기초 영어회화 ] \"아프다\", \"다치다\" - hurt(s) 의 기본활용과 발음" },
  { n: 38, id: "v2pQyesI_qY", title: "[ 기초영어회화 ] \"잠을 잘못 잔 것 같아. 목이 너무 아파.\"" },
  { n: 39, id: "BmKpL--OVXg", title: "[ 기초영어회화 ] 기분을 풀어주다 / 말이 잘못 나오다 / 마음을 상하게 하다" },
  { n: 40, id: "ZcuabDrVrIw", title: "[ 기초영어회화 ] 누구를 집으로 초대하다, 누구네 집에 놀러가다" },
  { n: 41, id: "V3yn8eUAHYk", title: "left - 시간이 조금 남았다 / 돈이 많이 안남았다 [ 기초영어회화 ]" },
  { n: 42, id: "FVWYx4w8QEQ", title: "[ 영어 | 간접의문문 ] PART 1 - 기초적인 이해와 활용" },
  { n: 43, id: "3Y3fLBziNiI", title: "[ 영어 | 간접의문문 ] PART 2 - 거기 몇시에 여는지 알아? / 거기 삼겹살을 파는지 모르겠네." },
  { n: 44, id: "YN7l3dg-oog", title: "[ 기초영어회화 ] - 젊었을 때 / 어렸을 때 / 학생이었을 때 / 나이가 들면서/들수록" },
  { n: 45, id: "bNqR7zgoc04", title: "[ 기초영어회화 ] '고민'에 대해서 영어로 표현하기" },
  { n: 46, id: "xumwjCeDRQE", title: "[ 기초영어회화 ] - 하는 것이 더 좋다 / 더 좋을거다 / 더 좋을 수도 있다" },
  { n: 47, id: "yK_MuPCqc5w", title: "[ 기초영어회화 ] \"이거 원래 이래?\" , \"응. 이거 원래 이래.\" - PART 1" },
  { n: 48, id: "ew_T9ts-ikI", title: "[ 기초영어회화 ] 이거 엄청 어렵다 + 원래 이래? = 이거 원래 이렇게 어려워?" },
  { n: 49, id: "f0G2pQAKuNk", title: "[ 기초영어회화 ] 연령대 - 30대 초/중/후반, 내 또래, 보통 키와 몸무게" },
  { n: 50, id: "ZWm1kpXs-nY", title: "[ 기초영어회화 ] \"오늘 이걸 못끝내면 주말에 출근해야 될 수도 있어요 😭.\"" },
  { n: 51, id: "g5Wv-YDqsxU", title: "[ 기초영어회화 ] -- 할 기회가 있었다 / 없었다" },
  { n: 52, id: "8zdLUDXuMHY", title: "[ 기초영어회화 ] 완료시제 연습 - \"아직/벌써\" + 완료시제" },
  { n: 53, id: "UGgpU3heTXc", title: "[ 생활 기초 영어어휘 ] carry - 가지고 다니다 / 들고 다니다 / 넣고 다니다" },
  { n: 54, id: "G6blEAxcZJQ", title: "[ 기초영어회화 ] 기초 영어 어휘 \"leave\"" },
  { n: 55, id: "awlESfrBeh4", title: "[ 기초 영어 단어 ] - happen" },
  { n: 56, id: "jHMtRMn3EI0", title: "[ 기초영어회화 ] \"조용한게 싫은가봐요.\" - PART 1" },
  { n: 57, id: "1085X__lj-I", title: "[ 기초영어회화 ]  leave on / even when / feel more comfortable with" },
  { n: 58, id: "1B6igT5zqPI", title: "[ 기초영어회화 ] - 구동사 기초 - run out of" },
  { n: 59, id: "pAex5fMSDsc", title: "영어 대명사 활용 연습 - they / them / ones / mine [기초영어회화]" },
  { n: 60, id: "mV_F2aqSSC8", title: "영어 표현력 업그레이드 - spend time + ing / waste time + ing" },
  { n: 61, id: "oiHcMCqoeXU", title: "[ 영어 표현 배우기 ] \"혼자서 / 스스로 알아서 / 직접\"" },
  { n: 62, id: "sec7DGM8M5I", title: "[ 기초영어회화 ] 수염을 없앨 의향이 있습니다" },
  { n: 63, id: "Q-YQr0c6Lw0", title: "[ 기초영어회화 ] talk / speak / tell / say" },
  { n: 64, id: "5WEAx-rYcbs", title: "[기초영어회화] \"wait\" - 기다리다 / 누구를 기다리다 / 누가 어떻게 하기를 기다리다" },
  { n: 65, id: "iFiSCaHxg1s", title: "[기초영어회화] -하기로 결정하다 / -하지 않기로 결정하다 / -언제/무엇을 하기로 결정하다 [[decide]]" },
  { n: 66, id: "SdEkD2eH5zg", title: "[기초영어회화] 날짜, 요일, 주에 대해서 말하기" },
  { n: 67, id: "oHQWA0Cw35I", title: "[기초영어회화] 거기 분위기가 좋아 / 거기는 사람들이 친절해 / 거기 상황이 지금 안좋아" },
  { n: 68, id: "TZe4fUKPPxY", title: "[ 기초영어회화 ] 먹어본 중에 가장 맛있는 피자 / 본 영화 중에 가장 재밌었다" },
  { n: 69, id: "B4e0xZZN2QE", title: "[ 기초영어회화 ] 전치사 활용 연습" },
  { n: 70, id: "O1YcgSj1abk", title: "[ 기초영어회화 ] 소유격 연습" },
  { n: 71, id: "gxZTTgEnkcE", title: "낯익다, 낯설다 [ 영어 회화 패턴 ] → 반복 듣고 따라 말하기 [ familiar 연습영상 ]" },
  { n: 72, id: "4QENSg-v7Dg", title: "기초영어회화 💬 시간이 많다 / 없다 / 충분하다 / 얼마 없다 / 조금 밖에 없다" },
  { n: 73, id: "GH8B7RN3WHA", title: "쉽게 따라할 수 있는 간단한 영어회화 TiP💡 --  \"볼일 보러 잠깐 나와 있어.\"" },
  { n: 74, id: "8sPG7Wf2dgU", title: "5분 영어로 💬 \"확실히 더 시원해졌어.\"" },
  { n: 75, id: "m9DcvA8rm0w", title: "단순한 영어 문장 → 섬세한 영어 문장 💡  할 일이 있다 👉🏻 몇 가지만 해결하면 된다" },
  { n: 76, id: "RtTe8SDH84Y", title: "학생 때 배워서 다 아는 영어? 🤔 NOT ONLY A BUT ALSO B" },
  { n: 77, id: "sIJAyQv4reg", title: "(don't) want to be + 4가지 패턴" },
  { n: 78, id: "0_rl8bVx0MU", title: "단수? 복수? the 붙여서?💡 영어 기본 문장 만들기" },
  { n: 79, id: "HWO6USt1n3g", title: "영어 실시간 말하기 연습" },
  { n: 80, id: "YPqYxDg0pRo", title: "실시간 영어 회화 강의 🔴 감각동사 연습 (5/30)" },
  { n: 81, id: "xUdP1_-Lj_Y", title: "(미니강의) \" 이번 주에 만나고 싶었는데 몸이 안 좋아서 다음 주에 만나기로 했어. \" (실시간 방송 클립)" },
  { n: 82, id: "oxcmKf9-GIk", title: "영어 말하기 운동 ➠ ~ 할 계획인데 (만약) 비가 오면 안 할 수도 있어" },
  { n: 83, id: "NM914y96H7g", title: "💪🏻 영어 말하기 운동 : ~ 할 생각인데 ➠ 무슨 일 생겨서 시간이 안 되면 ➠ 다음 주에 할 수도 있어" },
  { n: 84, id: "d38IA09xdws", title: "\" 가장 \" ➠ 영어로 말하기" },
  { n: 85, id: "tsAfITpS_xU", title: "기초 영어 회화 패턴⚡️show 누구 how to -- // 누구에게 -- 하는 방법을 보여 주다 / 가르쳐 주다" },
  { n: 86, id: "O6DxtN6M6Tg", title: "⏰ 📅 (PART 2) 영어 시간 표현⚡️ [ 실시간 온라인 영어학원 ]" },
  { n: 87, id: "vYV1f6nT_ao", title: "⟪ 실시간 온라인 영어학원 ⟫⚡️빈도와 시간에 대해서 말하기 연습" },
  { n: 88, id: "mwTOT6HDeLA", title: "⏰ 시간이 걸린다 / 💴 돈이 든다 ➠ 표현 방식이 같으니까 같이 연습하세요" },
  { n: 89, id: "idN6oZLwnsw", title: "⟪ 실시간 온라인 영어학원 ⟫⚡️관계에 대해서 말할 때 쓰는 영어표현" },
  { n: 90, id: "2Y8Lh1gVN0E", title: "기초 영어 문장 만들기⚡️빈도, 시간" },
  { n: 91, id: "an7IzNAc6CU", title: "⟪실시간 온라인 영어학원⟫💡영어 기초 다지기 ➠ 기본 문장 만들기 연습⚡️" },
  { n: 92, id: "Arz3JDNTLIo", title: "⟪ 실시간 온라인 영어학원 ⟫⚡️계획, 예정된 일, 약속한 일" },
  { n: 93, id: "rob0entVfoo", title: "영어 문장 만들기 + 자연스러운 표현 + 말하기 연습💡일정, 계획, 약속에 대해서 말하기" },
  { n: 94, id: "2ZQDp9IbJHw", title: "⟪ 실시간 온라인 영어 학원 ⟫💡걱정되는 것과 기대되는 것에 대해서 말하기" },
  { n: 95, id: "ifWfkeU9834", title: "⟪ 실시간 온라인 영어학원 ⟫⚡️기본 문장 : 시간표현 + 시제 연습" },
  { n: 96, id: "6F2lQkvELTg", title: "💡영어로 걱정 표현하기 ⟪ 기초 영어회화 / 영어 말하기 연습 ⟫" },
];
