// -- 96강 왕초보 영어회화 강의 데이터 --
// 출처: 라이브 아카데미 토들러 유튜브 재생목록 '기초 문장 만들기와 내용 확장'
// https://www.youtube.com/playlist?list=PLEzsBdrpZXC8tdzAqQHEQ66TocGI-Kagh
// desc: 영상 설명(창작자 작성)을 요약한 한두 문장 - AI 학습자료 생성 시 실제 강의 주제 컨텍스트로 사용됨
const LESSON96 = [
  { n: 1, id: "OGHo7apPWIY", title: "왕초보를 위한 영어회화 강의 - Lesson 001 [기본적인 문장 구성하기]", desc: "영어를 완전히 처음 배우는 사람들에게 '일반동사'로 문장 만드는 가장 기본 개념을 실생활 위주로 가르치는 강의입니다. 강의에서 실제로 쓰는 틀은 이렇습니다: 먼저 work(일하다)/study(공부하다)/cook(요리하다)/work out(운동하다) 같은 쉬운 동사로 'I work.'처럼 '본문장(주어+동사)'을 만들고, 그 다음 every day(매일)/on weekends(주말에)/in an office(사무실에서)/mainly with books(주로 책으로)/at home(집에서)/six hours a day(하루 6시간씩) 같은 시간·장소·방법을 나타내는 표현을 '+'로 붙여서 문장의 정보를 확장하는 연습을 합니다. (문법 용어보다 '본문장 + 확장 정보' 라는 실전 틀로 접근합니다)" },
  { n: 2, id: "yJg0rrmRZhA", title: "🌱영어회화 | 기초 영어 - 문장 만들기-  Lesson 002", desc: "Lesson 1에서 배운 '본문장 + 확장 정보' 틀을 그대로 쓰면서 두 가지를 추가로 배우는 강의입니다. ① 부정문: 동사 앞에 don't을 붙이고 확장 표현은 그대로 뒤에 둡니다 - 'I work.' → 'I don't work + on weekends.' ② 3인칭 단수 주어(he/she/it/사람이름)일 때는 동사에 -s/-es를 붙입니다 - 'He works.' / 'She studies.' / 'Jane cooks.' ③ 3인칭 단수의 부정문은 doesn't + 동사원형(-s 없이)으로 만듭니다 - 'He doesn't work.' / 'She doesn't study.' 'He works hard.' → 'He doesn't work hard.' 처럼 긍정/부정을 짝지어 비교하며 연습합니다." },
  { n: 3, id: "0R6tL0ESm_U", title: "기초 영어 | Lesson 003 | 실제 회화에서 be 동사의 기본적인 활용", desc: "Lesson 1~2의 일반동사 문장(본문장+확장정보) 뒤에, be동사(is/am/are)로 만든 짧은 문장을 '+'나 but으로 이어붙여서 자신의 감상·평가를 덧붙이는 실전 화법을 배우는 강의입니다. 예: 'I work almost 12 hours a day.' + 'It's tough.' / 'I don't work on weekends.' but 'I'm lucky.' / 'She exercises every day at home by herself.' + 'She's very healthy.' 일반동사로 사실을 말하고, be동사로 짧게 코멘트를 얹는 게 원어민이 실제 자주 쓰는 화법이라는 걸 강조합니다." },
  { n: 4, id: "c7_IqzxcaS0", title: "기초 영어 | Lesson 004 | 현재 / 과거 / 미래 시제", desc: "같은 문장을 현재/과거/미래로 바꿔가며 말하는 연습을 하는 강의입니다. 현재: 'I drive to work 2 or 3 times a week.' 과거: 'I drove to work yesterday / today / this morning.' (drive→drove처럼 동사 형태가 바뀌는 불규칙 변화 포함) 미래: 'be going to + 동사원형'을 써서 'I am going to drive to work.' 하나의 상황을 세 시제로 반복해서 말해보며 자연스럽게 시제 전환을 몸에 익힙니다." },
  { n: 5, id: "MY6Y2wiXSLA", title: "영어회화 | 기초 문장 구성하기 [Lesson 005] | be 동사로 인상 표현하기 + 과거/미래시제 적용", desc: "Lesson 1~4의 일반동사 문장과 Lesson 3의 be동사 인상 표현('+it's ~')을 합쳐서 과거/미래 시제까지 적용하는 응용 강의입니다. 예: 'I take the subway to work. I transfer 2 times. It's inconvenient.' (현재) → 'I transferred twice. It was inconvenient.' (과거: 일반동사는 -ed, be동사는 is→was로 동시에 바뀜) 같은 상황을 현재/과거로 반복하며 일반동사 시제 변화와 be동사 시제 변화를 함께 연습합니다." },
  { n: 6, id: "kOi2P-HQIKs", title: "\"~하고 싶다\", \"해야 된다\"를 영어로 말하기 | 영어 기초 문장 구성하기 | 영어회화 [LESSON 006]", desc: "본문장 중간에 'want to(~하고 싶다)'나 'have to(~해야 한다)'를 끼워넣어 의미를 확장하는 강의입니다. 문장 끝이 아니라 주어와 본동사 사이에 삽입합니다: 'I +want to+ live in Seoul.' / 'I +have to+ drink a lot of water.' 과거형은 want를 wanted로 바꾸고('I wanted to live in Seoul.'), 부정문은 didn't를 앞에 붙입니다('I didn't want to live in Seoul.' - want to 자체는 원형 유지)." },
  { n: 7, id: "_FeHK1Vd7KM", title: "영어로 질문하기 [Part1] - 기초적인 의문형/의문문 구성을 배워보자 | 영어회화 [LESSON 007]", desc: "일반동사 문장을 Yes/No 의문문으로 바꾸는 법을 배우는 강의입니다. 문장 맨 앞에 Do를 붙이고 동사는 원형 그대로 씁니다: 'I work.' → 'Do you work?' 주어가 3인칭 단수(he/she 등)면 Do 대신 Does를 쓰고 동사는 원형으로 돌아갑니다: 'Does she work on weekends?' 의문문 뒤에도 every day/on weekends/by myself 같은 확장 표현을 그대로 붙일 수 있다는 것까지 연습합니다." },
  { n: 8, id: "MDLG58YRPv4", title: "영어로 질문하기 [Part 2] [ LESSON #008 ] -- 초보영어회화 | 라이브 아카데미 토들러", desc: "일반동사 의문문에 시제를 적용하고 의문사(who/what/when/where/why/how)를 결합하는 강의입니다. 세 가지 틀: 1) 'Do you ~?' (현재, 평소에 하는지), 2) 'Did you ~?' (과거 - 3인칭이어도 Did+동사원형 그대로: 'Did she quit her job?'), 3) 'Are you going to ~?' (미래). 의문사는 문장 맨 앞에 붙입니다: 'What are you going to eat?'" },
  { n: 9, id: "pOggApqOz3Y", title: "영어로 질문하기 [Part 3] [ LESSON #009 ] -- 영어회화 | 라이브 아카데미 토들러", desc: "be동사 의문문에 과거/미래 시제를 적용하는 강의입니다. 'It's good.' → 과거는 Is를 Was로 바꿔 앞으로: 'Was it good?' 미래는 두 형태를 다룹니다 - 'It is going to be good.' → 'Is it going to be good?' (be going to는 그대로 두고 Is만 이동), 'It will be fun.' → 'Will it be fun?' (will을 앞으로). 원래 있던 be동사·조동사를 문장 맨 앞으로 옮기기만 하면 의문문이 된다는 원리를 반복 연습합니다." },
  { n: 10, id: "uPWsw5GIbtI", title: "[LESSON#10] - 영어 문장 연결하기 [PART 1]- and / so / because - [라이브 아카데미 토들러]", desc: "문장 두 개를 so/because로 자연스럽게 연결하는 강의입니다. because(이유): 'I was late because there was a lot of traffic.' (결과를 먼저 말하고 because+이유를 붙임). so(결과): 'There was a lot of traffic, so I got off.' (원인을 먼저 말하고 so+결과를 붙임 - because와 어순이 반대라는 게 핵심 포인트). 이유를 강조하고 싶으면 because, 결과를 강조하고 싶으면 so를 쓰는 식으로 의도에 따라 표현을 골라 쓰는 연습을 합니다." },
  { n: 11, id: "wjXyGcnx2G8", title: "[LESSON #11] 문맥을 만들어서 자연스러운 말의 흐름 익히기 - and / so / because - PART 2 [기초 영어회화]", desc: "지난 영상에 이어서 and / so / because 를 이용해서 문맥을 형성시켜 말의 흐름을 만들고 듣고 말하는 연습을 해봅니다." },
  { n: 12, id: "lIwZ3bkyr6s", title: "[LESSON#12] and / so / because 추가연습 - PART 3 | 영어회화 [라이브아카데미 토들러]", desc: "지난 영상에 이어서 and / so / because 로 문장을 이어줌으로써 말의 흐름을 만드는 연습을 계속해서 해봅니다." },
  { n: 13, id: "WSUM2yUsub8", title: "[LESSON #13 - PART 1] \"무엇이 있다/없다\" - there is(are) ~ there is(are) no ~", desc: "이번 영상에서는 '무엇이 있다/없다/많다/적다'를 영어로 말하는 것을 배워봅니다. there is(are), there is(are) no." },
  { n: 14, id: "5nwOP4D__rw", title: "\"there is\" - PART 2 [ LESSON #14 ] - 영어회화", desc: "\"무엇이 있다/없다/많다/별로 없다\"을 말할 때 항상 'there is/are'만 사용하지는 않는다. 상황에 따라 \"have\" 동사로 표현해야 하는 경우를 구분하는 법을 배우고 의문형을 만드는 연습을 합니다." },
  { n: 15, id: "Xg1fjoe0cXo", title: "[ LESSON #15 ] 영어회화 - 기초 문장 구성 - \"무엇을 하기 + 어떻다\"", desc: "\"잊어버리기 쉽다\", \"들고 다니기 불편하다\", \"집중하기 어렵다\"처럼 [무엇을 하기] + [어떻다]라는 기초적인 문장 구성을 배웁니다." },
  { n: 16, id: "hyHjOMAPmMs", title: "[ LESSON #16 ] something / somewhere / someone - 영어회화 기초 [라이브아카데미 토들러]", desc: "something / somewhere / someone이 일상적으로 얼마나 유용하게 사용되는지 배워봅니다." },
  { n: 17, id: "rFGmMnQFQaw", title: "[ LESSON #17 - PART 1 ] \"시간이 걸리다\", \"돈이 들다\" - [ 영어회화 / 라이브아카데미 토들러 ]", desc: "[시간이 걸리다]와 [돈이 들다]를 영어로 표현할 때 알아야 하는 여러가지 문장 구성과 유형을 배워봅니다." },
  { n: 18, id: "_49xUFx5n4M", title: "[ LESSON#17 - PART 2 ] - \"오래 걸려요?\" / \"얼마나 (오래) 걸려요?\"", desc: "시간이 오래 걸리는지, 얼마나 오래 걸리는지에 대해서 질문할 때 쓰는 의문문을 배우고 연습해봅니다." },
  { n: 19, id: "dpN0FfT8k7o", title: "[ LESSON #18 ] - 할 때 / 하기 전에 / 하고 나서 / 할 때까지 [ 라이브아카데미 토들러 / 영어회화 ]", desc: "when / after / before / until을 이용해서 \"~할 때, ~하고나서, 하기 전에, ~할 때까지\"를 표현하는 것을 배웁니다." },
  { n: 20, id: "tgAnPN_mf-k", title: "[LESSON#19 - Part 1] -  과거분사형 / 동명사형 - bored/boring", desc: "인상을 묘사할 때 형용사뿐 아니라 타동사를 과거분사형/동명사형으로 바꿔 쓰는 경우가 많은데, 그 가장 기본적인 개념을 세워봅니다." },
  { n: 21, id: "Ks0qJXeTCcA", title: "[ LESSON #19 - PART 2 ] \"짜증나\" - annoyed / annoying / frustrated / frustrating", desc: "[타동사]의 [과거분사형]과 [동명사형]으로 감정/기분을 말하는 예시를 \"짜증나다\"라는 주제로 계속 연습합니다." },
  { n: 22, id: "cHJpKhVnH-I", title: "[ LESSON #20 / 대화가이드 #003 ] - \"할게 있다/없다/많다\" - \"그때까지는 할게 별로 없다\"", desc: "\"할게 있다/없다/많다\"를 표현하는 대화 예시를 통해 연습합니다." },
  { n: 23, id: "F8vUB75aD34", title: "[ LESSON #21 ] - 예전에는 ~~ 었는데 지금은 ~~ | 자연스러운 말의 흐름 | 영어회화", desc: "일상적으로 자주 사용하는 말의 패턴 \"예전에는 ~~ 었는데 지금은 ~~\"을 배웁니다." },
  { n: 24, id: "yvWkEoHCdmE", title: "[ LESSON #22 ] - 중요한 영어 단어 \"spend\" - Part 1", desc: "'spend'라는 영어 단어의 가장 기초적인 의미와 활용을 배우는 2부 강의 중 PART 1. 왜 중요하고 어떻게 쓰는지 기본 개념과 예문을 연습합니다." },
  { n: 25, id: "vsoQ-MWFGZc", title: "[ LESSON #23 ] 'spend'  - Part 2 [ 영어회화 ]", desc: "영어에서 아주 중요한 단어인 'spend'에 대한 기초적인 활용을 이어서 배워봅니다." },
  { n: 26, id: "l_OIS5XaQCs", title: "LESSON #24 - 시간표현 PART 1 - 며칠 전에 / 몇달 후에 / 지금으로부터 몇년 뒤에 / 그저께(엊그제) / 모레", desc: "시간 표현 시리즈의 PART 1로, 시간에 대한 표현 중 가장 기본적인 패턴 몇 가지를 배웁니다 (며칠 전에/몇달 후에/그저께/모레)." },
  { n: 27, id: "vPpsH30SmZs", title: "감각동사 - PART 1 (기본개념) - look, sound, smell, taste, feel", desc: "look / sound / smell / taste / feel — 단순히 모양이나 소리를 말할 때만 쓰는 게 아니라, 보고 들은 것에 대한 인상/느낌을 말할 때도 많이 쓰인다는 기본 개념을 예문으로 세워봅니다." },
  { n: 28, id: "lo4YD4FASOM", title: "감각동사 - PART 2 - look like + 명사 / sound like + 완성형 문장", desc: "지난 강의에 이어 감각동사의 기본 유형을 배우는 PART 2. look like + 명사 표현을 배웁니다." },
  { n: 29, id: "GHlSaB3VzRE", title: "감각동사 PART 3 - 응용연습", desc: "PART 1과 PART 2에서 배운 내용과 'seem' 감각동사를 포함해서 응용연습을 해봅니다." },
  { n: 30, id: "KvuCt-u56Ww", title: "감각동사 - PART 4 - \"내가 보기에는 괜찮은데.\" , \"너가 듣기에는 어때?\"", desc: "실제 대화에서 감각동사를 자연스럽게 쓰려면 문맥 속 여러 어감과 뉘앙스를 알아야 합니다. PART 4에서 이어서 다룹니다." },
  { n: 31, id: "xY8-tOJu0GQ", title: "관계절 - PART 1 - 기본개념과 기본 구성 이해하기", desc: "관계절은 영어 구사 수준을 판단하는 중요한 기준 중 하나입니다. 관계절의 가장 기본적인 개념과 구성을 배웁니다." },
  { n: 32, id: "Iux513BJWLo", title: "관계절 PART 2 - 내가 듣는 음악, 내가 찾던 디자인, 새로 이사한 집", desc: "관계절에서 전치사를 살려야 하는 경우와 그 이유, 그리고 관사 the/a의 활용을 배웁니다." },
  { n: 33, id: "_2RMoPE92VY", title: "관계절 - PART 3 - 미국에 사는 친구 / 수영장이 있는 호텔 / 개봉하지 않은 영화", desc: "관계절에서 주어를 생략해야 하는 유형을 배웁니다." },
  { n: 34, id: "LhLO4mwkac8", title: "[ 대화가이드 #004 ] 관계절 - PART 4 - 자연스러운 대화 속에서 관계절을 연습하고 감잡기", desc: "관계절 PART 4에서는 PART 1-3에서 배운 내용을 하나의 대화 속에서 복습, 응용 연습을 합니다." },
  { n: 35, id: "W3V9TM6Vrj0", title: "[ 생활 영어 표현 ] \"거기는 음식이 맛있어\"를 영어로 표현하는 3가지 방식", desc: "\"거기는 음식이 맛있어\"라는 말을 영어로 표현하는 3가지 방식을 배웁니다." },
  { n: 36, id: "HsmLR7rZtTg", title: "(무엇)이 많다 / (무엇)을 많이 한다 - \"a lot of\"", desc: "\"a lot of\"라는 표현의 기본적인 활용을 복습하고 추가적인 활용을 배워봅니다." },
  { n: 37, id: "4IuQ53h9dwQ", title: "[ 기초 영어회화 ] \"아프다\", \"다치다\" - hurt(s) 의 기본활용과 발음", desc: "일상적으로 자주 쓰는 단어 hurt의 기본 활용과 발음을 연습합니다." },
  { n: 38, id: "v2pQyesI_qY", title: "[ 기초영어회화 ] \"잠을 잘못 잔 것 같아. 목이 너무 아파.\"", desc: "\"목을 다쳤어. 많이 아파\"에 이어 \"잠을 잘못 자다\"라는 표현을 배우고 이어서 말하는 연습을 합니다." },
  { n: 39, id: "BmKpL--OVXg", title: "[ 기초영어회화 ] 기분을 풀어주다 / 말이 잘못 나오다 / 마음을 상하게 하다", desc: "지난 강의들의 응용 복습이면서 추가 표현을 몇 가지 더 배우는 연습자료입니다 (기분을 풀어주다/말이 잘못 나오다/마음을 상하게 하다)." },
  { n: 40, id: "ZcuabDrVrIw", title: "[ 기초영어회화 ] 누구를 집으로 초대하다, 누구네 집에 놀러가다", desc: "누구네 집에 \"놀러가다\", 누구를 \"집으로 초대하다\"라고 할 때 'over'라는 단어의 활용을 배웁니다." },
  { n: 41, id: "V3yn8eUAHYk", title: "left - 시간이 조금 남았다 / 돈이 많이 안남았다 [ 기초영어회화 ]", desc: "\"시간이 많이 남았다\", \"돈이 별로 안남았다\"처럼 '남았다'를 표현할 때 'left'라는 단어로 말하는 법을 배웁니다." },
  { n: 42, id: "FVWYx4w8QEQ", title: "[ 영어 | 간접의문문 ] PART 1 - 기초적인 이해와 활용", desc: "생활 속에서 쓰이는 [간접의문문]을 가장 기초적인 선에서 이해하고 활용하는 법을 배웁니다." },
  { n: 43, id: "3Y3fLBziNiI", title: "[ 영어 | 간접의문문 ] PART 2 - 거기 몇시에 여는지 알아? / 거기 삼겹살을 파는지 모르겠네.", desc: "간접의문문의 다양한 형태에 대해 배웁니다 (거기 몇시에 여는지 알아? / 거기 삼겹살을 파는지 모르겠네)." },
  { n: 44, id: "YN7l3dg-oog", title: "[ 기초영어회화 ] - 젊었을 때 / 어렸을 때 / 학생이었을 때 / 나이가 들면서/들수록", desc: "\"젊었을 때\"를 \"when I was young\"이라고 흔히 표현하지만 은퇴할 나이가 아니면 어색합니다. 상황에 맞는 여러 표현을 배웁니다." },
  { n: 45, id: "bNqR7zgoc04", title: "[ 기초영어회화 ] '고민'에 대해서 영어로 표현하기", desc: "\"할지 말지\", \"지금 할지 나중에 할지\", \"어떻게 할지\" 같은 고민을 영어로 표현하는 법을 배웁니다." },
  { n: 46, id: "xumwjCeDRQE", title: "[ 기초영어회화 ] - 하는 것이 더 좋다 / 더 좋을거다 / 더 좋을 수도 있다", desc: "\"--하는 것이 더 좋다\", \"--하는 것이 더 좋을거다\", \"--하는 것이 더 좋을 수도 있다\"를 자연스럽게 표현하는 법을 배웁니다." },
  { n: 47, id: "yK_MuPCqc5w", title: "[ 기초영어회화 ] \"이거 원래 이래?\" , \"응. 이거 원래 이래.\" - PART 1", desc: "\"이거 원래 이래?\", \"응. 이건 원래 이래.\"라는 표현을 가장 기초적인 수준에서 배웁니다." },
  { n: 48, id: "ew_T9ts-ikI", title: "[ 기초영어회화 ] 이거 엄청 어렵다 + 원래 이래? = 이거 원래 이렇게 어려워?", desc: "\"이거 원래 이렇게 어려워?\", \"쟤 원래 저렇게 시끄러워?\", \"여기 원래 사람이 이렇게 많아?\" 같은 말을 어떻게 하는지 배웁니다." },
  { n: 49, id: "f0G2pQAKuNk", title: "[ 기초영어회화 ] 연령대 - 30대 초/중/후반, 내 또래, 보통 키와 몸무게", desc: "특정 사람의 연령대, 키, 몸무게에 대해 말하는 가장 기초적인 묘사법을 배웁니다." },
  { n: 50, id: "ZWm1kpXs-nY", title: "[ 기초영어회화 ] \"오늘 이걸 못끝내면 주말에 출근해야 될 수도 있어요 😭.\"", desc: "\"I have to\"가 조건절과 함께 쓰일 때는 미래시제나 might 같은 조동사와 함께 쓰는 것이 자연스럽다는 것을 배웁니다." },
  { n: 51, id: "g5Wv-YDqsxU", title: "[ 기초영어회화 ] -- 할 기회가 있었다 / 없었다", desc: "\"--을 할 기회가 있었다/없었다\"를 영어로 표현하는 다양한 패턴을 배웁니다." },
  { n: 52, id: "8zdLUDXuMHY", title: "[ 기초영어회화 ] 완료시제 연습 - \"아직/벌써\" + 완료시제", desc: "완료시제에 대한 감을 잡는 연습을 합니다 (\"아직/벌써\" + 완료시제)." },
  { n: 53, id: "UGgpU3heTXc", title: "[ 생활 기초 영어어휘 ] carry - 가지고 다니다 / 들고 다니다 / 넣고 다니다", desc: "일상 기초 영어 어휘 'carry'를 배웁니다 (가지고 다니다/들고 다니다/넣고 다니다)." },
  { n: 54, id: "G6blEAxcZJQ", title: "[ 기초영어회화 ] 기초 영어 어휘 \"leave\"", desc: "일상적으로 많이 쓰이는 영어 어휘 'leave'의 다양한 활용을 배웁니다." },
  { n: 55, id: "awlESfrBeh4", title: "[ 기초 영어 단어 ] - happen", desc: "기초 영어 단어 'happen'을 단순 의미가 아니라 대화체 흐름 속 실질적인 활용으로 배웁니다." },
  { n: 56, id: "jHMtRMn3EI0", title: "[ 기초영어회화 ] \"조용한게 싫은가봐요.\" - PART 1", desc: "\"I like it + when...\" / \"I don't like it + when...\" 패턴을 배우는 PART 1입니다." },
  { n: 57, id: "1085X__lj-I", title: "[ 기초영어회화 ]  leave on / even when / feel more comfortable with", desc: "leave on / even when / feel more comfortable with 표현을 실생활 예시로 배웁니다." },
  { n: 58, id: "1B6igT5zqPI", title: "[ 기초영어회화 ] - 구동사 기초 - run out of", desc: "기초 수준의 구동사인 'run out of'에 대해서 배웁니다." },
  { n: 59, id: "pAex5fMSDsc", title: "영어 대명사 활용 연습 - they / them / ones / mine [기초영어회화]", desc: "영어 학습 초기에 의외로 어려운 대명사(they/them/ones/mine)의 활용을 한국어와 비교하며 연습합니다." },
  { n: 60, id: "mV_F2aqSSC8", title: "영어 표현력 업그레이드 - spend time + ing / waste time + ing", desc: "\"I watched TV all day yesterday.\" 대신 \"I spent all day yesterday watching TV.\"처럼 spend/waste + time + ing로 업그레이드된 표현을 배웁니다." },
  { n: 61, id: "oiHcMCqoeXU", title: "[ 영어 표현 배우기 ] \"혼자서 / 스스로 알아서 / 직접\"", desc: "\"혼자서\", \"스스로\", \"알아서\", \"직접\" 같은 표현을 여러 예문으로 배웁니다." },
  { n: 62, id: "sec7DGM8M5I", title: "[ 기초영어회화 ] 수염을 없앨 의향이 있습니다", desc: "\"무엇을 할 의향(생각)이 있다(be willing to)\"라는 표현을 조건절과 함께 연습합니다." },
  { n: 63, id: "Q-YQr0c6Lw0", title: "[ 기초영어회화 ] talk / speak / tell / say", desc: "talk / speak / tell / say의 차이와 활용을 실생활 대화 예시로 배웁니다." },
  { n: 64, id: "5WEAx-rYcbs", title: "[기초영어회화] \"wait\" - 기다리다 / 누구를 기다리다 / 누가 어떻게 하기를 기다리다", desc: "'기다리다'를 말하는 'wait' 단어의 여러 문장 형식을 배웁니다." },
  { n: 65, id: "iFiSCaHxg1s", title: "[기초영어회화] -하기로 결정하다 / -하지 않기로 결정하다 / -언제/무엇을 하기로 결정하다 [[decide]]", desc: "decide가 choose나 select와 어떤 차이가 있는지, 기본 활용 패턴을 배웁니다." },
  { n: 66, id: "SdEkD2eH5zg", title: "[기초영어회화] 날짜, 요일, 주에 대해서 말하기", desc: "오늘이 수요일일 때 last Monday가 이틀 전 월요일인지 지난주 월요일인지는 원어민도 혼란스러워하는 부분입니다. 날짜/요일/주 표현을 기초부터 정리합니다." },
  { n: 67, id: "oHQWA0Cw35I", title: "[기초영어회화] 거기 분위기가 좋아 / 거기는 사람들이 친절해 / 거기 상황이 지금 안좋아", desc: "\"거기 음식 / 거기 사람들 / 거기 분위기\"처럼 자주 하는 말을 영어로 표현하는 법을 기초적인 선에서 배웁니다." },
  { n: 68, id: "TZe4fUKPPxY", title: "[ 기초영어회화 ] 먹어본 중에 가장 맛있는 피자 / 본 영화 중에 가장 재밌었다", desc: "\"내가 본 영화 중에 가장 재밌었다\", \"내가 먹어본 것 중에 가장 맛있는 피자다\" 같은 말을 영어로 하는 법을 배웁니다." },
  { n: 69, id: "B4e0xZZN2QE", title: "[ 기초영어회화 ] 전치사 활용 연습", desc: "전치사 활용을 실생활 대화 예시로 연습합니다." },
  { n: 70, id: "O1YcgSj1abk", title: "[ 기초영어회화 ] 소유격 연습", desc: "소유격을 실생활 대화 예시로 연습합니다." },
  { n: 71, id: "gxZTTgEnkcE", title: "낯익다, 낯설다 [ 영어 회화 패턴 ] → 반복 듣고 따라 말하기 [ familiar 연습영상 ]", desc: "[낯이 익다 / 낯설다 / 익숙하다] 등의 표현을 활용한 영어 회화 패턴을 반복 듣고 따라 말하며 연습합니다." },
  { n: 72, id: "4QENSg-v7Dg", title: "기초영어회화 💬 시간이 많다 / 없다 / 충분하다 / 얼마 없다 / 조금 밖에 없다", desc: "시간이 많다/없다/충분하다/얼마 없다/조금밖에 없다를 표현하는 법을 배웁니다." },
  { n: 73, id: "GH8B7RN3WHA", title: "쉽게 따라할 수 있는 간단한 영어회화 TiP💡 --  \"볼일 보러 잠깐 나와 있어.\"", desc: "\"볼일 보러 잠깐 나와 있어\" 같은 간단한 영어회화 팁을 대화 예시로 배웁니다." },
  { n: 74, id: "8sPG7Wf2dgU", title: "5분 영어로 💬 \"확실히 더 시원해졌어.\"", desc: "\"확실히 더 시원해졌어요.\"를 영어로 말하는 법을 배웁니다." },
  { n: 75, id: "m9DcvA8rm0w", title: "단순한 영어 문장 → 섬세한 영어 문장 💡  할 일이 있다 👉🏻 몇 가지만 해결하면 된다", desc: "\"I have something to do\"에서 \"I have some things to do\"처럼 단순한 문장을 좀 더 섬세한 문장으로 바꿔 표현하는 법을 배웁니다." },
  { n: 76, id: "RtTe8SDH84Y", title: "학생 때 배워서 다 아는 영어? 🤔 NOT ONLY A BUT ALSO B", desc: "NOT ONLY A BUT ALSO B 패턴을 실생활 예문으로 배웁니다." },
  { n: 77, id: "sIJAyQv4reg", title: "(don't) want to be + 4가지 패턴", desc: "(don't) want to be + 4가지 패턴을 예문으로 배웁니다." },
  { n: 78, id: "0_rl8bVx0MU", title: "단수? 복수? the 붙여서?💡 영어 기본 문장 만들기", desc: "a dog, dogs, the dog(s)처럼 단수/복수/관사를 구분하는 연습 방법을 배웁니다." },
  { n: 79, id: "HWO6USt1n3g", title: "영어 실시간 말하기 연습", desc: "실시간 방송으로 진행한 영어 말하기 연습 영상입니다." },
  { n: 80, id: "YPqYxDg0pRo", title: "실시간 영어 회화 강의 🔴 감각동사 연습 (5/30)", desc: "실시간 방송으로 진행한 감각동사 활용 연습 영상입니다." },
  { n: 81, id: "xUdP1_-Lj_Y", title: "(미니강의) \" 이번 주에 만나고 싶었는데 몸이 안 좋아서 다음 주에 만나기로 했어. \" (실시간 방송 클립)", desc: "실시간 방송에서 했던 연습 중 일부를 다룬 미니강의입니다 (\"이번 주에 만나고 싶었는데 몸이 안 좋아서 다음 주에 만나기로 했어\" 표현)." },
  { n: 82, id: "oxcmKf9-GIk", title: "영어 말하기 운동 ➠ ~ 할 계획인데 (만약) 비가 오면 안 할 수도 있어", desc: "얼마 전 실시간 방송 때 연습한 내용 중 일부입니다 (~ 할 계획인데 (만약) 비가 오면 안 할 수도 있어)." },
  { n: 83, id: "NM914y96H7g", title: "💪🏻 영어 말하기 운동 : ~ 할 생각인데 ➠ 무슨 일 생겨서 시간이 안 되면 ➠ 다음 주에 할 수도 있어", desc: "실시간 방송 연습 중 일부로, \"~ 할 생각인데 무슨 일 생겨서 시간이 안 되면 다음 주에 할 수도 있어\" 패턴을 배웁니다." },
  { n: 84, id: "d38IA09xdws", title: "\" 가장 \" ➠ 영어로 말하기", desc: "\"가장 (어떻다)\", \"제일 (어떻다)\"라는 말을 자연스럽게 영어로 표현하는 법을 배웁니다." },
  { n: 85, id: "tsAfITpS_xU", title: "기초 영어 회화 패턴⚡️show 누구 how to -- // 누구에게 -- 하는 방법을 보여 주다 / 가르쳐 주다", desc: "실시간 강의 중 일부로, show 누구 how to (누구에게 -- 하는 방법을 보여 주다/가르쳐 주다) 패턴을 배웁니다." },
  { n: 86, id: "O6DxtN6M6Tg", title: "⏰ 📅 (PART 2) 영어 시간 표현⚡️ [ 실시간 온라인 영어학원 ]", desc: "실시간 온라인 영어학원 방송에서 시간 표현을 연습하는 PART 2입니다." },
  { n: 87, id: "vYV1f6nT_ao", title: "⟪ 실시간 온라인 영어학원 ⟫⚡️빈도와 시간에 대해서 말하기 연습", desc: "실시간 온라인 영어학원 방송에서 빈도와 시간에 대해 말하는 연습입니다 (every other day/week/month 등)." },
  { n: 88, id: "mwTOT6HDeLA", title: "⏰ 시간이 걸린다 / 💴 돈이 든다 ➠ 표현 방식이 같으니까 같이 연습하세요", desc: "실시간 강의 중 일부로, 시간이 걸린다/돈이 든다는 표현 방식이 같다는 것을 함께 연습합니다." },
  { n: 89, id: "idN6oZLwnsw", title: "⟪ 실시간 온라인 영어학원 ⟫⚡️관계에 대해서 말할 때 쓰는 영어표현", desc: "실시간 온라인 영어학원 방송에서 관계에 대해 말할 때 쓰는 영어표현을 다룹니다." },
  { n: 90, id: "2Y8Lh1gVN0E", title: "기초 영어 문장 만들기⚡️빈도, 시간", desc: "최근 실시간 강의 중 일부로, 빈도와 시간 표현을 다룹니다." },
  { n: 91, id: "an7IzNAc6CU", title: "⟪실시간 온라인 영어학원⟫💡영어 기초 다지기 ➠ 기본 문장 만들기 연습⚡️", desc: "실시간 온라인 영어학원 방송에서 기본 문장 만들기를 연습합니다 (내일 아침 일찍 회의가 있어서 오늘 밤에는 평소보다 일찍 자려고)." },
  { n: 92, id: "Arz3JDNTLIo", title: "⟪ 실시간 온라인 영어학원 ⟫⚡️계획, 예정된 일, 약속한 일", desc: "실시간 온라인 영어학원 방송에서 계획, 예정된 일, 약속한 일 표현을 연습합니다 (I'm going to + V / I will)." },
  { n: 93, id: "rob0entVfoo", title: "영어 문장 만들기 + 자연스러운 표현 + 말하기 연습💡일정, 계획, 약속에 대해서 말하기", desc: "실시간 강의 중 일부로, 일정·계획·약속에 대해 말하는 자연스러운 표현과 말하기 연습을 다룹니다." },
  { n: 94, id: "2ZQDp9IbJHw", title: "⟪ 실시간 온라인 영어 학원 ⟫💡걱정되는 것과 기대되는 것에 대해서 말하기", desc: "실시간 온라인 영어학원 방송에서 걱정되는 것과 기대되는 것에 대해 말하는 표현을 연습합니다 (I'm really looking forward to it)." },
  { n: 95, id: "ifWfkeU9834", title: "⟪ 실시간 온라인 영어학원 ⟫⚡️기본 문장 : 시간표현 + 시제 연습", desc: "실시간 온라인 영어학원 방송에서 기본 문장의 시간표현과 시제를 연습합니다 (recently/lately)." },
  { n: 96, id: "6F2lQkvELTg", title: "💡영어로 걱정 표현하기 ⟪ 기초 영어회화 / 영어 말하기 연습 ⟫", desc: "최근 실시간 강의 중 일부로, 영어로 걱정을 표현하는 법을 연습합니다." },
];
